name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Roda o workflow quando há push na branch principal

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Login no GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/made-report:latest .

      # Publicação da imagem no GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/made-report:latest
